### ISSUE TITLE
config.php

### ISSUE THREAD

**Issue by huxuan** [CAPU-ENG/CAPUBBS#13]
Use config.php instead of raw username/password for database connection.

**Comment by QwertyJack** [comment]
done @20150322

**Comment by huxuan** [comment]
Actually, @zhzhzoo ‘s PR haven't been merged, so this issue remains open.

**Comment by QwertyJack** [comment]
Is it done now?

**Comment by huxuan** [comment]
Well done. @QwertyJack
